version: '3.6'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - mynetwork
  worker:
    build: .
    container_name: "worker"
    depends_on:
      - rabbitmq
    restart: on-failure
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge